network_routes:
- network_type: IPv4
  description: My first route
  network_id: Route 1
  enabled: true
  peer_groups:
    - g2
  domains:
    - example.com
  metric: 9999
  masquerade: true
  groups:
    - g1
  keep_route: true
